### PR TITLE
Update

### PR DESCRIPTION
**Pull request by miaoYZheng**
Hi Julien,

Sorry for the wait, just some minor replacements of dead links.

Best,
Yiyun

### CODE REVIEW

**Comment by julprat** [comment]
That was quick ! Thanks. Now you can take your time. You don’t have more comments about the writing, presentation, content?

Let’s meet next Monday.

Best,
Julien

From: Yiyun ZHENG ***@***.***>
Reply to: julprat/Tutorials_hub ***@***.***>
Date: Wednesday 11 September 2024 at 14:41
To: julprat/Tutorials_hub ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [julprat/Tutorials_hub] Update (PR #1)


Hi Julien,

Sorry for the wait, just some minor replacements of dead links.

Best,
Yiyun

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/julprat/Tutorials_hub/pull/1

Commit Summary

  *   95f6640<https://github.com/julprat/Tutorials_hub/pull/1/commits/95f6640227bb0212dccae7dc0be5c4a31f82b457> Update Tutorial_2.ipynb
  *   8d0e987<https://github.com/julprat/Tutorials_hub/pull/1/commits/8d0e987321c4b0eb75191c36849c14876e8dccb5> Update Tutorial_2.ipynb
  *   4849a5a<https://github.com/julprat/Tutorials_hub/pull/1/commits/4849a5a7cbc70e9f766d7858ed41e5755b990262> Update Tutorial_3.ipynb
  *   1dbe626<https://github.com/julprat/Tutorials_hub/pull/1/commits/1dbe6263d977e6fb1a9c26524c7a99b0ea9ab619> Update Tutorial_4.ipynb
  *   804290b<https://github.com/julprat/Tutorials_hub/pull/1/commits/804290ba040c319d19bd0804c67b88cee55fd300> Update Tutorial_6.ipynb

File Changes

(4 files<https://github.com/julprat/Tutorials_hub/pull/1/files>)

  *   M Tutorial_2.ipynb<https://github.com/julprat/Tutorials_hub/pull/1/files#diff-ca12a87f71f7778d923238c48f428bad00ff68eaf9ce4fd0d738922d961263ac> (2)
  *   M Tutorial_3.ipynb<https://github.com/julprat/Tutorials_hub/pull/1/files#diff-6718f9c12ef4a7f4372c9c03d3fd47281eb4ad18a6ce3ed33ef187a2e30bfde5> (2)
  *   M Tutorial_4.ipynb<https://github.com/julprat/Tutorials_hub/pull/1/files#diff-2227a5eeece8af50f513df9c3b724b9786eca126e1cc8658d86b5e8648642bf4> (6)
  *   M Tutorial_6.ipynb<https://github.com/julprat/Tutorials_hub/pull/1/files#diff-00198622034c8f60afffd3d8e94882b093957aca3e50d6599a6c015ba683d39f> (2)

Patch Links:

  *   https://github.com/julprat/Tutorials_hub/pull/1.patch
  *   https://github.com/julprat/Tutorials_hub/pull/1.diff

**Comment by miaoYZheng** [comment]
Hi Julien, 

Yes, I wasn't aware that you would like comments on the content too, I can certainly do that before our meeting on Monday. Also I still owe you the written documents on my research. 

See you next week. 

Best, 
Yiyun

**Review by julprat — APPROVED** [review]

**Comment by julprat** [comment]
Hi,

I have merged your update with the main branch. Thanks for the corrections.

I could not make it today but I will be at the department tomorrow. If you are around, let’s meet in the morning, around 10 AM.

Best,
Julien

From: Yiyun ZHENG ***@***.***>
Reply to: julprat/Tutorials_hub ***@***.***>
Date: Thursday 12 September 2024 at 11:27
To: julprat/Tutorials_hub ***@***.***>
Cc: julien prat ***@***.***>, Comment ***@***.***>
Subject: Re: [julprat/Tutorials_hub] Update (PR #1)

Hi Julien,

Yes, I wasn't aware that you would like comments on the content too, I can certainly do that before our meeting on Monday. Also I still owe you the written documents on my research.

See you next week.

Best,
Yiyun

**Comment by miaoYZheng** [comment]
Hi, 

I realised that was the case since you are usually around in the morning. 

Sorry I did not have time to add more comments, I was not very successful in debugging the NFT tutorial over the weekend, Emanuele also tried to help. 

I cannot be at the office tomorrow, but I will be there on Wednesday and Thursday, would that work for you? 

Best wishes, 
Yiyun

**Comment by julprat** [comment]
Hi,

I will be there on Thursday, but quite busy with teaching and meetings.

Emanuele is still around? I haven’t heard from him since NY.

Best,
Julien

From: Yiyun ZHENG ***@***.***>
Reply to: julprat/Tutorials_hub ***@***.***>
Date: Monday 16 September 2024 at 20:55
To: julprat/Tutorials_hub ***@***.***>
Cc: julien prat ***@***.***>, State change ***@***.***>
Subject: Re: [julprat/Tutorials_hub] Update (PR #1)

Hi,

I realised that was the case since you are usually around in the morning.

Sorry I did not have time to add more comments, I was not very successful in debugging the NFT tutorial over the weekend, Emanuele also tried to help.

I cannot be at the office tomorrow, but I will be there on Wednesday and Thursday, would that work for you?

Best wishes,
Yiyun

**Comment by miaoYZheng** [comment]
Hi, 

I will be around if you have a minute. Yes, he came last week, he will leave France at the end of this month. 

Best, 
Yiyun

**Pull request merged**
